### DISCUSSION TITLE
Trouble Integrating Python Wifi Connect

### DISCUSSION THREAD

**Discussion by keenanjohnson** [maggie0002/balena-device-ui#138] [Q&A]
Hey everyone!

I was trying to add the start-interface to my open-pet-cam project I'm starting here, and I am having some problems getting the python wifi connect to work. 

I've added it as a git submodule and then added it to [the docker compose here.](https://github.com/keenanjohnson/open-pet-cam/blob/main/docker-compose.yml) 

I have verified that it is indeed running in the balena console, but it doesn't appear in the UI.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/2559382/235851977-bc7be848-7d7a-476f-9d8a-bdbaa405cc78.png">

Checking the logs I see some connection refused errors, though it did some the python container started:

```
 balena-cam  (Press CTRL+C to quit)
 python-wifi-connect  [2023-04-27 03:33:41] - [INFO] - Checking for previously configured Wi-Fi connections...
 python-wifi-connect  [2023-04-27 03:33:52] - [INFO] - A Wi-Fi connection or hotspot is already active.
 python-wifi-connect  [2023-04-27 03:33:52] - [INFO] - Ready...
 python-wifi-connect  [2023-04-27 03:33:52] - [INFO] - Listening on 0.0.0.0 port 9090
 balena-starter-interface  ExpressJS: listening on port 80
 pan-tilt  192.168.0.142 - - [29/Apr/2023 00:40:32] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.142 - - [29/Apr/2023 00:40:32] "GET /favicon.ico HTTP/1.1" 404 -
 pan-tilt  192.168.0.30 - - [30/Apr/2023 18:20:45] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.30 - - [30/Apr/2023 18:20:45] "GET /favicon.ico HTTP/1.1" 404 -
 pan-tilt  192.168.0.142 - - [02/May/2023 04:33:52] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.142 - - [03/May/2023 02:48:50] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.142 - - [03/May/2023 02:51:08] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.142 - - [03/May/2023 02:51:08] "GET /favicon.ico HTTP/1.1" 404 -
 pan-tilt  192.168.0.142 - - [03/May/2023 02:54:15] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.142 - - [03/May/2023 02:55:06] "GET / HTTP/1.1" 200 -
 pan-tilt  192.168.0.142 - - [03/May/2023 02:55:53] "GET / HTTP/1.1" 200 -
 balena-starter-interface  ExpressJS: 2023-05-03 02:57:17:5717 error: connect ECONNREFUSED 127.0.0.1:9090
```

Any pointers on what I'm doing wrong? @maggie44 ?

Thanks!

### Docker Compose File

```
version: '2'
services:
  balena-cam:
    build: ./balena-cam
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
  pan-tilt:
    build: ./pantilt
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
  balena-starter-interface:
    build:
      context: .
      dockerfile: interface/Dockerfile.bsi
    environment:
      SET_HOSTNAME: "balena" # Optional. Changes the device hostname. UI will become accesible on `balena.local`.
      UDEV: on # Enables ability to auto mount USB drives in to the container
    restart: always
    ports:
      - "80:80"
    volumes:
      - "bdi_db:/app/db" # Stores UI database files
      - "bdi_storage:/app/storage" # Storage for the File Manager. See docs for more info.
    privileged: true # This can be removed if not using the USB mounting feature
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
  python-wifi-connect:
    environment:
      ## Listening IP and port ##
      PWC_HOST: "0.0.0.0"
      PWC_PORT: 9090

      ## Hotspot details ##
      PWC_HOTSPOT_SSID: "Python Wi-Fi Connect"
      #PWC_HOTSPOT_PASSWORD: "my-hotspot-password" # Optional. Must be 8 characters or more.

      ## Try to automatically connect to a Wi-Fi network on first boot ##
      #PWC_AC_SSID: "network-name" # Compulsory for this feature
      #PWC_AC_USERNAME: "username" # Optional
      #PWC_AC_PASSWORD: "your-password" # Optional. Must be 8 characters or more.

      ## Wi-Fi Interface ##
      #PWC_INTERFACE: "wlan0" # By default it automatically detects the interface.

      ## Enable/Disable LED interaction ##
      #PWC_LED: "on"

      ## Required system variables ##
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile
    network_mode: "host"
    restart: on-failure
    volumes:
      - "py_wifi_connect_db:/app/db" # Optional if not setting the hotspot ssid and password via the API
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
    privileged: true # This can be removed if you do not need the LED indicator.

volumes:
  bdi_db:
  bdi_storage:
  py_wifi_connect_db:
```
